#version: '3.8'

services:
  spark-iceberg:
    image: bitnami/spark:3.3
    container_name: spark-iceberg
    environment:
      - SPARK_MODE=master
    ports:
      - "4041:4040"
      - "7078:7077"
    volumes:
      - ./spark-iceberg:/bitnami
      - ./jars:/opt/spark/jars  
      - ./spark-iceberg/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    entrypoint: >
      /bin/bash -c "
      mkdir -p /opt/spark/jars &&
      cp /opt/bitnami/spark/jars/* /opt/spark/jars &&
      exec /opt/bitnami/scripts/spark/entrypoint.sh /opt/bitnami/scripts/spark/run.sh
      "


  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:4.0.0-alpha-2
    container_name: hive-metastore
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_URIS: thrift://hive-metastore:9083
      METASTORE_DB_TYPE: postgres
      METASTORE_DB_HOST: postgres
      METASTORE_DB_NAME: metastore
      METASTORE_DB_USER: hive
      METASTORE_DB_PASSWORD: hive
    command: /opt/hive/bin/hive --service metastore

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - hive-metastore
      - minio
    ports:
      - "8080:8080"
    volumes:
      - ./trino-config:/etc/trino
      - ./trino-data:/var/trino/data

  spark:
    image: bitnami/spark:3.3
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"
      - "7077:7077"
    volumes:
      - ./spark-data:/bitnami

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    command: webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hive:hive@postgres:5432/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hive:hive@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 'sqMWtKdYP0LzRkGJrxPJoAmIbfYTwYX-TZh4Ah5RsAY='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

volumes:
  minio_data:
  postgres_data:
  trino_data:
